### ISSUE TITLE
[Bug] OSError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by JackMa01** [kaixindelele/ChatPaper#10]
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\PIL\JpegImagePlugin.py", line 643, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\chat_paper.py", line 415, in <module>
    main(args=args)
  File ".\chat_paper.py", line 397, in main
    reader1.summary_with_chat(paper_list=paper_list)
  File ".\chat_paper.py", line 173, in summary_with_chat
    first_image, ext = paper.get_image_path()
  File "E:\project\ChatPaper\get_paper_from_pdf.py", line 85, in get_image_path
    image.save(open(im_path, "wb"))
  File "D:\Anaconda\lib\site-packages\PIL\Image.py", line 2431, in save
    save_handler(self, fp, filename)
  File "D:\Anaconda\lib\site-packages\PIL\JpegImagePlugin.py", line 646, in _save
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG

**Comment by kaixindelele** [comment]
如果你不使用gitee上传图片的话，把这部分代码注释掉吧~~没用上的~
