### ISSUE TITLE
KeyError: 'Introduction'

### ISSUE THREAD

**Issue by HansBug** [kaixindelele/ChatPaper#145]
Here is the error log, maybe some paper do not have `introduction` information?

```
mlb5b 2023-04-03T05:04:47.899Z max_font_sizes [9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 10.958900451660156, 23.91029930114746]
mlb5b 2023-04-03T05:04:48.220Z section_page_dict {'INTRODUCTION': 0, 'PRELIMINARIES': 1, 'RELATED WORK': 1, 'Algorithm Classification': 1, 'Forward Matching Algorithms': 1, 'Backward Matching Algorithms': 1, 'DESIGN OF BOP': 2, 'Basic Idea': 2, 'BOP for Forward Counting-based Algorithm': 2, 'Extension for Backward Marking-based Algorithm': 2, 'Implementation Considerations': 2, 'Complexity Analysis': 3, 'EXPERIMENTS': 3, 'Test Benches': 3, 'Setup': 3, 'Results and Analysis': 3, 'Memory Usage': 5, 'CONCLUSION': 5}
mlb5b 2023-04-03T05:04:48.231Z 0 INTRODUCTION 0
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 0 1
mlb5b 2023-04-03T05:04:48.231Z 1 PRELIMINARIES 1
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 1 1
mlb5b 2023-04-03T05:04:48.231Z 2 RELATED WORK 1
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 1 1
mlb5b 2023-04-03T05:04:48.231Z 3 Algorithm Classification 1
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 1 1
mlb5b 2023-04-03T05:04:48.231Z 4 Forward Matching Algorithms 1
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 1 1
mlb5b 2023-04-03T05:04:48.231Z 5 Backward Matching Algorithms 1
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 1 2
mlb5b 2023-04-03T05:04:48.231Z 6 DESIGN OF BOP 2
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 2 2
mlb5b 2023-04-03T05:04:48.231Z 7 Basic Idea 2
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 2 2
mlb5b 2023-04-03T05:04:48.231Z 8 BOP for Forward Counting-based Algorithm 2
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 2 2
mlb5b 2023-04-03T05:04:48.231Z 9 Extension for Backward Marking-based Algorithm 2
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 2 2
mlb5b 2023-04-03T05:04:48.231Z 10 Implementation Considerations 2
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 2 3
mlb5b 2023-04-03T05:04:48.231Z 11 Complexity Analysis 3
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 3 3
mlb5b 2023-04-03T05:04:48.231Z 12 EXPERIMENTS 3
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 3 3
mlb5b 2023-04-03T05:04:48.231Z 13 Test Benches 3
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 3 3
mlb5b 2023-04-03T05:04:48.231Z 14 Setup 3
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 3 3
mlb5b 2023-04-03T05:04:48.231Z 15 Results and Analysis 3
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 3 5
mlb5b 2023-04-03T05:04:48.231Z 16 Memory Usage 5
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 5 5
mlb5b 2023-04-03T05:04:48.231Z 17 CONCLUSION 5
mlb5b 2023-04-03T05:04:48.231Z start_page, end_page: 5 6
mlb5b 2023-04-03T05:04:48.233Z Traceback (most recent call last):
mlb5b 2023-04-03T05:04:48.233Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
mlb5b 2023-04-03T05:04:48.233Z     output = await app.get_blocks().process_api(
mlb5b 2023-04-03T05:04:48.233Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
mlb5b 2023-04-03T05:04:48.233Z     result = await self.call_function(
mlb5b 2023-04-03T05:04:48.233Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
mlb5b 2023-04-03T05:04:48.233Z     prediction = await anyio.to_thread.run_sync(
mlb5b 2023-04-03T05:04:48.233Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
mlb5b 2023-04-03T05:04:48.233Z     return await get_asynclib().run_sync_in_worker_thread(
mlb5b 2023-04-03T05:04:48.233Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
mlb5b 2023-04-03T05:04:48.233Z     return await future
mlb5b 2023-04-03T05:04:48.233Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
mlb5b 2023-04-03T05:04:48.233Z     result = context.run(func, *args)
mlb5b 2023-04-03T05:04:48.233Z   File "app.py", line 778, in upload_pdf
mlb5b 2023-04-03T05:04:48.233Z     paper_list = [Paper(path=file, sl=section_list)]
mlb5b 2023-04-03T05:04:48.233Z   File "app.py", line 98, in __init__
mlb5b 2023-04-03T05:04:48.233Z     self.parse_pdf()
mlb5b 2023-04-03T05:04:48.233Z   File "app.py", line 116, in parse_pdf
mlb5b 2023-04-03T05:04:48.233Z     self.section_text_dict.update({"paper_info": self.get_paper_info()})
mlb5b 2023-04-03T05:04:48.233Z   File "app.py", line 125, in get_paper_info
mlb5b 2023-04-03T05:04:48.233Z     introduction_text = self.section_text_dict['Introduction']
mlb5b 2023-04-03T05:04:48.233Z KeyError: 'Introduction'
```

**Comment by kaixindelele** [comment]
这个报错在我们主脚本里面消除了，在抱抱脸的还没有更新~
