### ISSUE TITLE
huggingface 私有化部署 返回错误

### ISSUE THREAD

**Issue by zuowanbushiwo** [kaixindelele/ChatPaper#159]
![image](https://user-images.githubusercontent.com/3354428/230259891-36fe1398-45a7-4926-9631-8149c3625ef1.png)
这个是应该怎么解决。
在API-KEY 界面显示的 key 是一个有效的key

**Comment by zuowanbushiwo** [comment]
看日志信息如下：
56vkr 2023-04-06T02:46:21.840Z   File "app.py", line 778, in upload_pdf
56vkr 2023-04-06T02:46:21.840Z     paper_list = [Paper(path=file, sl=section_list)]
56vkr 2023-04-06T02:46:21.840Z   File "app.py", line 98, in __init__
56vkr 2023-04-06T02:46:21.840Z     self.parse_pdf()
56vkr 2023-04-06T02:46:21.840Z   File "app.py", line 116, in parse_pdf
56vkr 2023-04-06T02:46:21.840Z     self.section_text_dict.update({"paper_info": self.get_paper_info()})
56vkr 2023-04-06T02:46:21.840Z   File "app.py", line 125, in get_paper_info
56vkr 2023-04-06T02:46:21.840Z     introduction_text = self.section_text_dict['Introduction']
56vkr 2023-04-06T02:46:21.840Z KeyError: 'Introduction

**Comment by zuowanbushiwo** [comment]
换了一篇文章用报这个错误，看日志 好像还解析一些了，但是最后还是报错了。
56vkr 2023-04-06T03:02:53.822Z Traceback (most recent call last):
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
56vkr 2023-04-06T03:02:53.822Z     output = await app.get_blocks().process_api(
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
56vkr 2023-04-06T03:02:53.822Z     result = await self.call_function(
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
56vkr 2023-04-06T03:02:53.822Z     prediction = await anyio.to_thread.run_sync(
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
56vkr 2023-04-06T03:02:53.822Z     return await get_asynclib().run_sync_in_worker_thread(
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
56vkr 2023-04-06T03:02:53.822Z     return await future
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
56vkr 2023-04-06T03:02:53.822Z     result = context.run(func, *args)
56vkr 2023-04-06T03:02:53.822Z   File "app.py", line 778, in upload_pdf
56vkr 2023-04-06T03:02:53.822Z     paper_list = [Paper(path=file, sl=section_list)]
56vkr 2023-04-06T03:02:53.822Z   File "app.py", line 96, in __init__
56vkr 2023-04-06T03:02:53.822Z     self.pdf = fitz.open(self.path)  # pdf文档
56vkr 2023-04-06T03:02:53.822Z   File "/home/user/.local/lib/python3.8/site-packages/fitz/fitz.py", line 3959, in __init__
56vkr 2023-04-06T03:02:53.822Z     raise EmptyFileError(msg)
56vkr 2023-04-06T03:02:53.822Z fitz.fitz.EmptyFileError: cannot open empty document
56vkr 2023-04-06T03:02:58.308Z Traceback (most recent call last):
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
56vkr 2023-04-06T03:02:58.308Z     output = await app.get_blocks().process_api(
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
56vkr 2023-04-06T03:02:58.308Z     result = await self.call_function(
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
56vkr 2023-04-06T03:02:58.308Z     prediction = await anyio.to_thread.run_sync(
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
56vkr 2023-04-06T03:02:58.308Z     return await get_asynclib().run_sync_in_worker_thread(
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
56vkr 2023-04-06T03:02:58.308Z     return await future
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
56vkr 2023-04-06T03:02:58.308Z     result = context.run(func, *args)
56vkr 2023-04-06T03:02:58.308Z   File "app.py", line 778, in upload_pdf
56vkr 2023-04-06T03:02:58.308Z     paper_list = [Paper(path=file, sl=section_list)]
56vkr 2023-04-06T03:02:58.308Z   File "app.py", line 96, in __init__
56vkr 2023-04-06T03:02:58.308Z     self.pdf = fitz.open(self.path)  # pdf文档
56vkr 2023-04-06T03:02:58.308Z   File "/home/user/.local/lib/python3.8/site-packages/fitz/fitz.py", line 3959, in __init__
56vkr 2023-04-06T03:02:58.308Z     raise EmptyFileError(msg)
56vkr 2023-04-06T03:02:58.308Z fitz.fitz.EmptyFileError: cannot open empty document
