### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by yuebaiqinghui** [kaixindelele/ChatPaper#162]
Traceback (most recent call last):
  File "D:\ChatPaper\app.py", line 10, in <module>
    from chat_arxiv import ArxivParams, chat_arxiv_main
  File "D:\ChatPaper\chat_arxiv.py", line 12, in <module>
    import fitz
  File "D:\ChatPaper\venv\Lib\site-packages\fitz\__init__.py", line 11, in <module>
    from fitz.fitz import *
  File "D:\ChatPaper\venv\Lib\site-packages\fitz\fitz.py", line 17, in <module>
    from . import _fitz
ImportError: cannot import name '_fitz' from partially initialized module 'fitz' (most likely due to a circular import) (D:\ChatPaper\venv\Lib\site-packages\fitz\__init__.py)

python版本是3.11.3 ，是一定要换3.9吗

**Comment by WangRongsheng** [comment]
你需要安装：
```python
pip install PyMuPDF
```
