### ISSUE TITLE
python chat_reviewer.py 报错

### ISSUE THREAD

**Issue by crankler** [kaixindelele/ChatPaper#172]
你好，谢谢你们的分享。
我在使用软件进行论文review时候，出现这种错误：
```
python chat_reviewer.py --paper_path "D:\xxx.pdf"    
------------------paper_num: 1------------------
0 xxx.pdf
Experimental, Results
Traceback (most recent call last):
  File "chat_reviewer.py", line 195, in <module>
    chat_reviewer_main(args=reviewer_args)
  File "chat_reviewer.py", line 181, in chat_reviewer_main
    reviewer1.review_by_chatgpt(paper_list=paper_list)
  File "chat_reviewer.py", line 73, in review_by_chatgpt
    chat_review_text = self.chat_review(text=text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "chat_reviewer.py", line 129, in chat_review
    text_token = len(self.encoding.encode(text))
  File "C:\Users\ROMA-MobileStation-1\AppData\Roaming\Python\Python38\site-packages\tiktoken\core.py", line 114, in encode
    return self._core_bpe.encode(text, allowed_special)
**UnicodeEncodeError: 'utf-8' codec can't encode characters in position 8530-8533: surrogates not allowed**
```

我想请问下，这种错误位置的报错：**UnicodeEncodeError: 'utf-8' codec can't encode characters in position 8530-8533: surrogates not allowed** 怎么才能显示出具体报错的内容是什么？（即是否能够增加功能，同时显示报错位置和对应的内容）？

谢谢回复，
祝好！

**Comment by crankler** [comment]
已解决，发现是overleaf下有的图片被识别错误导致
