### ISSUE TITLE
Proxy Unknown

### ISSUE THREAD

**Issue by river7816** [kaixindelele/ChatPaper#188]
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/114122443/233054902-d9e0cf77-22c0-4e4a-962b-d61cd794e954.png">
有没有什么办法能设置proxy代理，比如设置proxy：http或者https那种

```
Traceback (most recent call last):
  File "C:\Users\river\OneDrive\桌面\ChatPaper-main\chat_paper.py", line 531, in <module>
    chat_paper_main(args=paper_args)
  File "C:\Users\river\OneDrive\桌面\ChatPaper-main\chat_paper.py", line 474, in chat_paper_main
    reader1 = Reader(key_word=args.key_word,
  File "C:\Users\river\OneDrive\桌面\ChatPaper-main\chat_paper.py", line 72, in __init__
    self.encoding = tiktoken.get_encoding("gpt2")
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\tiktoken_ext\openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\tiktoken\load.py", line 68, in data_gym_to_mergeable_bpe_ranks
    vocab_bpe_contents = read_file_cached(vocab_bpe_file).decode()
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\tiktoken\load.py", line 41, in read_file_cached
    contents = read_file(blobpath)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\tiktoken\load.py", line 19, in read_file
    return requests.get(blobpath).content
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\requests\adapters.py", line 193, in proxy_manager_for
    manager = self.proxy_manager[proxy] = proxy_from_url(
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\urllib3\poolmanager.py", line 492, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "D:\miniforge3\envs\chatpaper\lib\site-packages\urllib3\poolmanager.py", line 429, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None
```

**Comment by river7816** [comment]
os.environ["http_proxy"] = "http://<代理ip>:<代理端口>" os.environ["https_proxy"] = "http://<代理ip>:<代理端口>" 已解决，不好意思没认真看
