### ISSUE TITLE
Mac M1运行报错

### ISSUE THREAD

**Issue by Dx-wmc** [kaixindelele/ChatPaper#2]
Mac M1运行报错
无法正常使用

代码：`python chat_paper.py --pdf_path ./test.pdf`
输出：
```
Key word: reinforcement learning
Query: all: ChatGPT robot
Sort: SortCriterion.Relevance
Traceback (most recent call last):
  File "/Users/dx/workdir/software/ChatPaper/chat_paper.py", line 412, in <module>
    main(args=args)
  File "/Users/dx/workdir/software/ChatPaper/chat_paper.py", line 382, in main
    paper_list = [Paper(path=args.pdf_path)]
  File "/Users/dx/workdir/software/ChatPaper/get_paper_from_pdf.py", line 14, in __init__
    self.title = self.get_title()
  File "/Users/dx/workdir/software/ChatPaper/get_paper_from_pdf.py", line 121, in get_title
    font_size = block["lines"][0]["spans"][0]["size"] # 获取第一行第一段文字的字体大小
IndexError: list index out of range
```
这有办法解决吗

**Comment by kaixindelele** [comment]
我怀疑这个是pdf文档的问题，从报错信息来看，是pdf中没有读取到标题。你换个英文版本的论文试试？或者用我默认的demo.pdf试试？

**Comment by Dx-wmc** [comment]
> 我怀疑这个是pdf文档的问题，从报错信息来看，是pdf中没有读取到标题。你换个英文版本的论文试试？或者用我默认的demo.pdf试试？

可以了，感谢！
