### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 687651 (char 687650)

### ISSUE THREAD

**Issue by MCCY0001** [kaixindelele/ChatPaper#275]
PS C:\Docs\projects\git_projects\ChatPaper> python chat_arxiv.py --query "chatgpt robots" --page_num 2 --max_results 3 --days 20
Traceback (most recent call last):
  File "C:\Docs\projects\git_projects\ChatPaper\chat_arxiv.py", line 753, in <module>
    chat_arxiv_main(args=arxiv_args)
  File "C:\Docs\projects\git_projects\ChatPaper\chat_arxiv.py", line 726, in chat_arxiv_main
    reader1 = Reader(key_word=args.key_word,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Docs\projects\git_projects\ChatPaper\chat_arxiv.py", line 339, in __init__
    self.encoding = tiktoken.get_encoding("gpt2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Application\anaconda\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
  File "C:\Application\anaconda\Lib\site-packages\tiktoken_ext\openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Application\anaconda\Lib\site-packages\tiktoken\load.py", line 85, in data_gym_to_mergeable_bpe_ranks
    encoder_json = json.loads(read_file_cached(encoder_json_file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Application\anaconda\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Application\anaconda\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Application\anaconda\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 687651 (char 687650)

这是什么原因，前面的都按照教程配置好了

**Comment by kingbeam** [comment]
请问你解决了吗
