### ISSUE TITLE
SCIPDF不支持苹果芯片

### ISSUE THREAD

**Issue by sowelswl** [kaixindelele/ChatPaper#278]
serve_grobid.sh 运行的时候报错，主要因为<Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/weilisong/Documents/GitHub/ChatPaper/scipdf_parser-master/grobid-0.6.2/grobid-home/lib/mac-64/libwapiti.dylib
>
看目录感觉是因为mac-64/libwapiti.dylib只支持macos的intel x86_64的芯片，而不支持apple chip的机型

’‘’
(base) scipdf_parser-master % bash serve_grobid.sh
Configuration(s) specified but the install task does not exist in project :grobid-core.
Configuration(s) specified but the install task does not exist in project :grobid-home.
Configuration(s) specified but the install task does not exist in project :grobid-service.
Configuration(s) specified but the install task does not exist in project :grobid-trainer.
> Task :grobid-core:compileJava UP-TO-DATE
> Task :grobid-core:processResources UP-TO-DATE
> Task :grobid-core:classes UP-TO-DATE
> Task :grobid-core:jar UP-TO-DATE
> Task :grobid-service:compileJava UP-TO-DATE
> Task :grobid-service:processResources UP-TO-DATE
> Task :grobid-service:classes UP-TO-DATE

> Task :grobid-service:run FAILED
00:13:34.349 [main] WARN org.grobid.service.main.GrobidServiceApplication - Expected 2 arguments: [0]-server, [1]-<path to config.yaml>
00:13:34.350 [main] INFO org.grobid.service.main.GrobidServiceApplication - Found conf path: /Users/weilisong/Documents/GitHub/ChatPaper/scipdf_parser-master/grobid-0.6.2/grobid-service/config/config.yaml
00:13:34.351 [main] WARN org.grobid.service.main.GrobidServiceApplication - Running with default arguments: "server" "/Users/weilisong/Documents/GitHub/ChatPaper/scipdf_parser-master/grobid-0.6.2/grobid-service/config/config.yaml"
00:13:34.351 [main] INFO org.grobid.service.main.GrobidServiceApplication - Configuration file: /Users/weilisong/Documents/GitHub/ChatPaper/scipdf_parser-master/grobid-0.6.2/grobid-service/config/config.yaml
INFO  [2023-10-09 16:13:34,979] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2023-10-09 16:13:34,981] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2023-10-09 16:13:34,983] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: grobidAssets for path /*
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/weilisong/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/eeb69005da379a10071aa4948c48d89250febb07/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  [2023-10-09 16:13:35,181] com.hubspot.dropwizard.guicier.DropwizardModule: Added guice injected health check: org.grobid.service.resources.HealthResource
INFO  [2023-10-09 16:13:35,186] org.grobid.core.utilities.GrobidProperties: environment variables overrides: {}
INFO  [2023-10-09 16:13:35,187] org.grobid.service.GrobidRestService: Initiating Servlet GrobidRestService
INFO  [2023-10-09 16:13:35,188] org.grobid.core.main.LibraryLoader: Loading external native sequence labelling library
INFO  [2023-10-09 16:13:35,191] org.grobid.core.main.LibraryLoader: Loading Wapiti native library...
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.UnsatisfiedLinkError: Can't load library: /Users/weilisong/Documents/GitHub/ChatPaper/scipdf_parser-master/grobid-0.6.2/grobid-home/lib/mac-64/libwapiti.dylib
  at org.grobid.service.GrobidRestService.<init>(GrobidRestService.java:69)
  at org.grobid.service.modules.GrobidServiceModule.configure(GrobidServiceModule.java:30) (via modules: com.google.inject.util.Modules$CombinedModule -> org.grobid.service.modules.GrobidServiceModule)
  while locating org.grobid.service.GrobidRestService

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at com.hubspot.dropwizard.guicier.GuiceBundle$Builder.lambda$new$0(GuiceBundle.java:152)
	at com.hubspot.dropwizard.guicier.GuiceBundle.run(GuiceBundle.java:106)
	at com.hubspot.dropwizard.guicier.GuiceBundle.run(GuiceBundle.java:34)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at org.grobid.service.main.GrobidServiceApplication.main(GrobidServiceApplication.java:107)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/weilisong/Documents/GitHub/ChatPaper/scipdf_parser-master/grobid-0.6.2/grobid-home/lib/mac-64/libwapiti.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at org.grobid.core.main.LibraryLoader.load(LibraryLoader.java:130)
	at org.grobid.core.factory.AbstractEngineFactory.init(AbstractEngineFactory.java:68)
	at org.grobid.service.GrobidRestService.<init>(GrobidRestService.java:79)
	at org.grobid.service.GrobidRestService$$FastClassByGuice$$d8fc2784.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 12 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-service:run'.
> Process 'command '/opt/homebrew/Cellar/openjdk@11/11.0.20.1/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
6 actionable tasks: 1 executed, 5 up-to-date
‘’‘

**Comment by kaixindelele** [comment]
感谢提供报错信息，我当时在Windows下试过是失败的，Ubuntu可以，但macos没有看到有人失败过。
所以以为macos和Ubuntu应该差不多，看来我天真了。
不知道docker会不会好一些，实在不行用用学术版GPT的网页版全文翻译吧：
https://academic.chatwithpaper.org/
