### ISSUE TITLE
运行python chat_paper.py --pdf_path "demo.pdf" 错误

### ISSUE THREAD

**Issue by szl666** [kaixindelele/ChatPaper#49]
运行python chat_paper.py --pdf_path "demo.pdf" 时出现以下问题：
Traceback (most recent call last):
  File "D:\chatpdf\ChatPaper-main\chat_paper.py", line 468, in <module>
    main(args=args)
  File "D:\chatpdf\ChatPaper-main\chat_paper.py", line 416, in main
    reader1 = Reader(key_word=args.key_word,
  File "D:\chatpdf\ChatPaper-main\chat_paper.py", line 47, in __init__
    self.encoding = tiktoken.get_encoding("gpt2")
  File "D:\anaconda\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "D:\anaconda\lib\site-packages\tiktoken_ext\openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
  File "D:\anaconda\lib\site-packages\tiktoken\load.py", line 68, in data_gym_to_mergeable_bpe_ranks
    vocab_bpe_contents = read_file_cached(vocab_bpe_file).decode()
  File "D:\anaconda\lib\site-packages\tiktoken\load.py", line 41, in read_file_cached
    contents = read_file(blobpath)
  File "D:\anaconda\lib\site-packages\tiktoken\load.py", line 19, in read_file
    return requests.get(blobpath).content
  File "D:\anaconda\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by clorsh** [comment]
我也是这个问题

**Comment by iu-x** [comment]
我也是SSLError

**Comment by tenthousands** [comment]
pip install urllib3==1.25.11
