### ISSUE TITLE
运行本地文件夹批量总结： 运行chat_paper.py， 比如：  python chat_paper.py --pdf_path "your_absolute_path"时程序报错

### ISSUE THREAD

**Issue by m1homo** [kaixindelele/ChatPaper#50]
报错信息如下
Traceback (most recent call last):
  File "F:\chatpaper\ChatPaper\chat_paper.py", line 468, in <module>
    main(args=args)
  File "F:\chatpaper\ChatPaper\chat_paper.py", line 433, in main
    paper_list.append(Paper(path=os.path.join(root, filename)))
  File "F:\chatpaper\ChatPaper\get_paper_from_pdf.py", line 17, in __init__
    self.parse_pdf()
  File "F:\chatpaper\ChatPaper\get_paper_from_pdf.py", line 33, in parse_pdf
    self.section_text_dict.update({"paper_info": self.get_paper_info()})
  File "F:\chatpaper\ChatPaper\get_paper_from_pdf.py", line 42, in get_paper_info
    introduction_text = self.section_text_dict['Introduction']
KeyError: 'Introduction'

**Comment by kaixindelele** [comment]
这个问题是因为这篇论文的Introduction前面没有数字序号，导致没法识别。这个需要修改一下这一行代码：
https://github.com/kaixindelele/ChatPaper/blob/ad990108d012c4ffbd45bdc3e46288ecce8f67b6/get_paper_from_pdf.py#L117
从
if 1 < len(point_split_list) < 5 and (point_split_list[0] in self.roman_num or point_split_list[0] in self.digit_num):
变为：
if 1 < len(point_split_list) < 5:
也许能解决这个问题，但也可能会引起新的bug.

**Comment by m1homo** [comment]
好的谢谢

**Comment by m1homo** [comment]
我尝试了一下，还是不行
