### ISSUE TITLE
您好，我尝试批量读取本地文件，但是报错了

### ISSUE THREAD

**Issue by tiangongdao2077** [kaixindelele/ChatPaper#58]
Traceback (most recent call last):
    main(args=args)
  File "chat_paper.py", line 433, in main
    paper_list.append(Paper(path=os.path.join(root, filename)))
  File "H:\学习\ChatPaper-main\get_paper_from_pdf.py", line 15, in __init__
    self.pdf = fitz.open(self.path) # pdf文档
  File "D:\software\Anaconda3\lib\site-packages\fitz\fitz.py", line 3962, in __init__
    _fitz.Document_swiginit(self, _fitz.new_Document(filename, stream, filetype, rect, width, height, fontsize))
fitz.fitz.FileDataError: cannot open broken document
可以汇总论文，但是fitz打不开pdf，环境没啥问题
下载论文并批量并总结没有问题，本地总结就会报错

**Comment by kaixindelele** [comment]
我猜是你的路径有问题，建议贴出你的命令行输入

**Comment by QYQSDTC** [comment]
我批量读报错，只读一个文件又没问题

批量命令` python chat_paper.py --pdf_path "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/Arxiv_daily/daily_arxiv/2023-03-19/"`

只读一个文件命令` python chat_paper.py --pdf_path "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/Arxiv_daily/daily_arxiv/2023-03-19/2303_08918  A CEERS Discovery of an Accreting Supermassive Black Hole 570 Myr after  the Big Bang_ Identifying a Progenitor of Massive z > 6 Quasars.pdf"`

```bash
Traceback (most recent call last):
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/chat_paper.py", line 468, in <module>
    main(args=args)
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/chat_paper.py", line 433, in main
    paper_list.append(Paper(path=os.path.join(root, filename)))
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/get_paper_from_pdf.py", line 17, in __init__
    self.parse_pdf()
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/get_paper_from_pdf.py", line 33, in parse_pdf
    self.section_text_dict.update({"paper_info": self.get_paper_info()})
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/get_paper_from_pdf.py", line 42, in get_paper_info
    introduction_text = self.section_text_dict['Introduction']
KeyError: 'Introduction'
```

**Comment by kaixindelele** [comment]
这个诡异的bug是因为我们的代码有逻辑问题，我调整下，你更新下就好了

**Comment by tiangongdao2077** [comment]
> 这个诡异的bug是因为我们的代码有逻辑问题，我调整下，你更新下就好了

PS H:\du\ChatPaper-main> python chat_paper.py --pdf_path "H:\du\ChatPaper-main\pdf_files\Knowledge graph-2023-03-18-12"          
Key word: reinforcement learning
Query: all: ChatGPT robot
Sort: SortCriterion.Relevance
root: H:\du\ChatPaper-main\pdf_files\Knowledge graph-2023-03-18-12 dirs: [] files: ['$μ_text{KG}$_ A Library for Multi-source Knowledge Graph Embeddings and Applications.pdf',
 省略若干，目前正常
依次列出论文，，
Traceback (most recent call last):
  File "chat_paper.py", line 469, in <module>
    main(args=args)
  File "chat_paper.py", line 434, in main
    paper_list.append(Paper(path=os.path.join(root, filename)))
  File "H:\du\ChatPaper-main\get_paper_from_pdf.py", line 15, in __init__
    self.pdf = fitz.open(self.path) # pdf文档
  File "D:\software\Anaconda3\lib\site-packages\fitz\fitz.py", line 3962, in __init__
    _fitz.Document_swiginit(self, _fitz.new_Document(filename, stream, filetype, rect, width, height, fontsize))
fitz.fitz.FileDataError: cannot open broken document
最后还是报错，跟前面同学很像，读一个文件可以，但是读一批不行，而且报错问题不同，不是'Introduction'，而是打不开cannot open broken document，路径啥的没问题，更新代码也没效果

**Comment by QYQSDTC** [comment]
我更新后依然有错
```bash
Traceback (most recent call last):
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/chat_paper.py", line 468, in <module>
    main(args=args)
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/chat_paper.py", line 433, in main
    paper_list.append(Paper(path=os.path.join(root, filename)))
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/get_paper_from_pdf.py", line 17, in __init__
    self.parse_pdf()
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/get_paper_from_pdf.py", line 33, in parse_pdf
    self.section_text_dict.update({"paper_info": self.get_paper_info()})
  File "/Users/qyq/Library/Mobile Documents/com~apple~CloudDocs/Development/ChatPaper/get_paper_from_pdf.py", line 42, in get_paper_info
    introduction_text = self.section_text_dict['Introduction']
KeyError: 'Introduction'
```
