### ISSUE TITLE
私有化部署后报错

### ISSUE THREAD

**Issue by wangzuohao** [kaixindelele/ChatPaper#66]
采用私有化部署，上次PDF后后报错，错误内容如下，还需要做什么配置吗：
im_path: image.png
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/ChatPaper/deploy/Private/app.py", line 619, in upload_pdf
    sum_info = reader.summary_with_chat(paper_list=paper_list)
  File "/root/ChatPaper/deploy/Private/app.py", line 446, in summary_with_chat
    summary_text += "<summary>" + chat_summary_text
TypeError: can only concatenate str (not "tuple") to str

**Comment by Crazybean-lwb** [comment]
补充一下：
![image](https://user-images.githubusercontent.com/22042825/227403480-0dbbba26-b213-4235-9256-0a240e046eb6.png)
这里也有一处tuple处理不妥当
