### ISSUE TITLE
[Bug] openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4218 tokens. Please reduce the length of the messages.

### ISSUE THREAD

**Issue by JackMa01** [kaixindelele/ChatPaper#7]
Traceback (most recent call last):
  File ".\chat_paper.py", line 412, in <module>
    main(args=args)
  File ".\chat_paper.py", line 394, in main
    reader1.summary_with_chat(paper_list=paper_list)
  File ".\chat_paper.py", line 200, in summary_with_chat
    chat_method_text = self.chat_method(text=text)
  File "D:\Anaconda\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\Anaconda\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\Anaconda\lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "D:\Anaconda\lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "D:\Anaconda\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\Anaconda\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "D:\Anaconda\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File ".\chat_paper.py", line 284, in chat_method
    response = openai.ChatCompletion.create(
  File "D:\Anaconda\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Anaconda\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Anaconda\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\Anaconda\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "D:\Anaconda\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4218 tokens. Please reduce the length of the messages.

**Comment by kaixindelele** [comment]
这个是字符串长度超过了最大token数量了，要么换一篇文章，要么将代码里的2500换成更小的2000，这样可能会降低生成的质量~~，回头我把这个好好调整一下。

**Comment by ChenghuiS** [comment]
> 这个是字符串长度超过了最大token数量了，要么换一篇文章，要么将代码里的2500换成更小的2000，这样可能会降低生成的质量~~，回头我把这个好好调整一下。

chatgpt api的token数量限制是4096，为什么代码里写成2500*4啊，这不是很容易超出最大长度限制吗~~
还有openai文档里有具体怎么计算输入文本的token数量，可以参考这个链接： `https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb`

**Comment by kaixindelele** [comment]
是的，我统计的是单词数2500*4，英文单词数和token的大致对应关系是这个数量，所以我们现在把提示词都换成英文。
