### ISSUE TITLE
运行中的错误

### ISSUE THREAD

**Issue by Chetni** [kaixindelele/ChatPaper#84]
在`apikey.ini` 修改了api之后运行：
`python3 chat_paper.py --pdf_path /Users/chentianma/Desktop/PDF`
出现报错：`Traceback (most recent call last):
  File "/Users/chentianma/Documents/GitHub/ChatPaper/chat_paper.py", line 478, in <module>
    main(args=args)    
    ^^^^^^^^^^^^^^^
  File "/Users/chentianma/Documents/GitHub/ChatPaper/chat_paper.py", line 446, in main
    reader1.summary_with_chat(paper_list=paper_list)
  File "/Users/chentianma/Documents/GitHub/ChatPaper/chat_paper.py", line 245, in summary_with_chat
    htmls.append(chat_conclusion_text)
                 ^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'chat_conclusion_text' where it is not associated with a value
`
请问是怎么个事

**Comment by Chetni** [comment]
重新运行了一下，卡在论文文件夹不动了，展示了里面的具体文件名

**Comment by Chetni** [comment]
成功了，

**Comment by Jalen-Zhong** [comment]
遇到了同样的问题，请描述一下解决方案，感谢！

**Comment by Chetni** [comment]
项目更新了，但是输出好像有点问题：
[https://www.icloud.com.cn/iclouddrive/01duSodAApgEzoz9ag8K3B1Cw#export](url)
